# Generated by Django 6.0.3 on 2026-03-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_api', '0002_car_verified_alter_car_model_alter_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cars', models.ManyToManyField(to='garage_api.car')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_api.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
