openapi: 3.0.3
info:
  title: Garage API
  version: 1.0.0
  description: The best api out there for garage management
paths:
  /api/admin-dashboard/:
    get:
      operationId: admin_dashboard_retrieve
      tags:
      - admin-dashboard
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/cars/:
    get:
      operationId: cars_list
      tags:
      - cars
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarNestedRead'
          description: ''
    post:
      operationId: cars_create
      tags:
      - cars
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Car'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Car'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
  /api/cars/{id}/:
    get:
      operationId: cars_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarNestedRead'
          description: ''
    put:
      operationId: cars_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Car'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Car'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
    patch:
      operationId: cars_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCar'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
    delete:
      operationId: cars_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - cars
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/cars/stats/:
    get:
      operationId: cars_stats_retrieve
      tags:
      - cars
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/manufacturers/:
    get:
      operationId: manufacturers_list
      tags:
      - manufacturers
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManufacturerNestedRead'
          description: ''
    post:
      operationId: manufacturers_create
      tags:
      - manufacturers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Manufacturer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Manufacturer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Manufacturer'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Manufacturer'
          description: ''
  /api/parts/:
    get:
      operationId: parts_list
      tags:
      - parts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'
          description: ''
    post:
      operationId: parts_create
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Part'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Part'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
  /api/parts/{id}/:
    get:
      operationId: parts_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    put:
      operationId: parts_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Part'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Part'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Part'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    patch:
      operationId: parts_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPart'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPart'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPart'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
          description: ''
    delete:
      operationId: parts_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this part.
        required: true
      tags:
      - parts
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        model:
          type: string
          maxLength: 100
          minLength: 2
        verified:
          type: boolean
        year:
          type: integer
          maximum: 2147483647
          minimum: 1900
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        manufacturer:
          type: integer
      required:
      - created_at
      - id
      - manufacturer
      - model
      - price
      - updated_at
      - year
    CarNestedRead:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        manufacturer:
          allOf:
          - $ref: '#/components/schemas/Manufacturer'
          readOnly: true
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        model:
          type: string
          maxLength: 100
          minLength: 2
        verified:
          type: boolean
        year:
          type: integer
          maximum: 2147483647
          minimum: 1900
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
      required:
      - created_at
      - id
      - manufacturer
      - model
      - parts
      - price
      - updated_at
      - year
    Manufacturer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 100
        country:
          type: string
          maxLength: 100
        founded_year:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
      required:
      - country
      - created_at
      - id
      - name
      - updated_at
    ManufacturerNestedRead:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cars:
          type: array
          items:
            $ref: '#/components/schemas/Car'
          readOnly: true
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 100
        country:
          type: string
          maxLength: 100
        founded_year:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
      required:
      - cars
      - country
      - created_at
      - id
      - name
      - parts
      - updated_at
    Part:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 100
        serial_number:
          type: string
          maxLength: 100
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        manufacturer:
          type: integer
        cars:
          type: array
          items:
            type: integer
      required:
      - cars
      - created_at
      - id
      - manufacturer
      - name
      - price
      - serial_number
      - updated_at
    PatchedCar:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        model:
          type: string
          maxLength: 100
          minLength: 2
        verified:
          type: boolean
        year:
          type: integer
          maximum: 2147483647
          minimum: 1900
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        manufacturer:
          type: integer
    PatchedPart:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          maxLength: 100
        serial_number:
          type: string
          maxLength: 100
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        manufacturer:
          type: integer
        cars:
          type: array
          items:
            type: integer
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
